name: Terraform k8

on: workflow_dispatch

env:
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
  TF_VAR_cluster_name: "k8-cluster"
  TF_VAR_region: "europe-west3"
  TF_VAR_network: "gke-network"
  TF_VAR_subnetwork: "gke-subnet"
  TF_VAR_ip_range_pods_name: "ip-range-pods"
  TF_VAR_ip_range_services_name: "ip-range-services"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform apply -destroy -auto-approve